import type { Metadata } from "next";
import { Luckiest_Guy, Fredoka } from "next/font/google";
import "./globals.css";

const header = Luckiest_Guy({ subsets: ["latin"], weight: "400", variable: "--font-header" });
const normal = Fredoka({ subsets: ["latin"], weight: ["300", "400", "500", "600", "700"], variable: "--font-normal" });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${header.variable} ${normal.variable} antialiased bg-background flex items-center`}>
        {children}
      </body>
    </html>
  );
}
